### ISSUE TITLE
Demo failing to register

### ISSUE THREAD

**Issue by gilfuser** [binbytes/nuxt-chat-app#1]
Hi!
Very inspiring project. Thank you for sharing it.
I just would like to let you know that the online working app is failing. The errors are:
```
The resource https://chat.binbytes.com/_nuxt/manifest.7b96659a9338ba9f2f70.js was 
preloaded using link preload but not used within a few seconds from the window's load 
event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
and
```
GET https://chat-server.binbytes.com/socket.io/?EIO=3&transport=polling&t=MLiRfEr 0 ()
```
I'm here to learn from your code, so I unfortunately I can't help figuring out whats happening.

best regards,
Gil

**Comment by nikkanetiya** [comment]
@gilfuser Good to find that this repo. help you for learn and thanks for reminding me, it simply because we just transferred our server few days ago and I have not started backend server of chat yet(So live demo will not work). I will make it working tomorrow for sure.

**Comment by nikkanetiya** [comment]
@gilfuser Its up & running. You can take a look at live demo, This is not a perfect project for production but its good place to start with.
